print("------------------------------------------------")
print("Python has entered the building")
print("Let the party begin!")
print("Jeff Bankston")
print("------------------------------------------------")